name: Auto Create Branch on Issue Assignment

on:
  issues:
    types: [assigned]

permissions:
  contents: write
  issues: write

jobs:
  create-feature-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Branch from Issue
        uses: subhamay-bhattacharyya-gha/create-branch-test@main
        with:
          base-branch: main
        secrets:
          git-token: ${{ secrets.GIT_TOKEN }}
