name: Auto Create Branch on Issue Assignment
run-name: Create Feature Branch by ${{ github.actor }} on ${{ github.ref_name }}

# on:
#   issues:
#     types: [assigned]

on:
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - uses: subhamay-bhattacharyya-gha/create-branch-test@main
        with:
          api-endpoint: /repos/octocat/Hello-World
          github-token: ${{ secrets.GITHUB_TOKEN }}



# permissions:
#   contents: write
#   issues: write

# jobs:
#   create-feature-branch:
#     name: "Create Feature Branch"
#     runs-on: ubuntu-latest
#     steps:
#       - name: Auto Branch from Issue
#         run: echo "Hello World !"
        
#         uses: subhamay-bhattacharyya-gha/create-branch-test@main
#         with:
#           base-branch: main
#         secrets:
#           git-token: ${{ secrets.GIT_TOKEN }}
